SEAN_AWS_ACCESS_KEY = "AKIAIKA2ZXOGMITYB2IA"
SEAN_AWS_SECRET_KEY = "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"
SEAN_AWS_BUCKET = "electionaire-ync-test"

AWS_ACCESS_KEY = "AKIAJXGGSCNDCIRVMZIQ"
AWS_SECRET_KEY = "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"
AWS_BUCKET = "electionaire"
